#!/bin/bash

ROOTFS=$(realpath "`pwd`/`dirname $0`/rootfs")

PROC="$ROOTFS/proc"
SYS="$ROOTFS/sys"
DEV="$ROOTFS/dev"

mount | grep $PROC > /dev/null || mount -t proc proc $PROC
mount | grep $SYS > /dev/null || mount -t sysfs sys $SYS
mount | grep $DEV > /dev/null || mount -o bind /dev $DEV

chroot $ROOTFS /bin/bash --login

mount | grep $PROC > /dev/null && umount $PROC
mount | grep $SYS > /dev/null && umount $SYS
mount | grep $DEV > /dev/null && umount $DEV
